# my_list= [96, 94, 99, 78, 14, 63, 73, 70, 38, 3, 53, 20, 27, 32, 89]
# n = len(my_list)

# for i in range(n):
#     for j in range(n-1):
#         if my_list[j] < my_list[j+1]:
#             my_list[j], my_list[j+1] = my_list[j+1], my_list[j]

# print(my_list)


nums={"A":1,"B":3,"C":3,"D":2,"E":1,"F":4,"G":2,"H":4,"I":1,"J":8,"K":5,"L":1,"M":3,"N":1,"O":1,"P":3,
      "Q":1,"R":1,"S":1,"T":1,"U":1,"V":4,
"W":4,"X":8,"Y":4,"Z":10}
