# my_list= [87, 71, 85, 55, 77, 68, 76, 86, 56, 41, 43, 14, 5, 90, 37, 32, 60, 81, 34, 28, 29]
# n = len(my_list)

# for i in range(n):
#     for j in range(n-1):
#         if my_list[j] < my_list[j+1]:
#             my_list[j], my_list[j+1] = my_list[j+1], my_list[j]

# print(my_list)




# nums={"A":1,"B":3,"C":3,"D":2,"E":1,"F":4,"G":2,"H":4,"I":1,"J":8,"K":5,"L":1,"M":3,"N":1,"O":1,"P":3,
# "Q":1,"R":1,"S":1,"T":1,"U":1,"V":4,"W":4,"X":8,"Y":4,"Z":10}


        



# def testing(nums,word):
#         score=0
#         for letter in word:
#                 score+=nums[letter]
#         return score
# count=1
# while count <=5:
#         word=input(f"What is the word?({count}):").upper()
#         total=testing(nums,word)
#         print(f"The score of your ({count}) word is {total}")
#         count+=1

